### ISSUE TITLE
-framework flag is only for Apple clang

### ISSUE THREAD

**Issue by keychera** [rayandrews/opengl-graphics#1]
[source](https://stackoverflow.com/questions/32170861/framework-command-line-option-in-cmake)

yo @rayandrews

**Comment by rayandrew** [comment]
yes, i will upload it soon for the fixes using CMakeLists

**Comment by keychera** [comment]
I uploaded my own fix in the new pull req, how about that

**Comment by rayandrew** [comment]
This issue has been fixed at this [commit](https://github.com/rayandrews/opengl-graphics/commit/50ede884d0b7a9e1da9f7a3bbcf0ce268b0c73e5)

Ty for pointing @keychera
